<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6aJFUxs\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6aJFUxs/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6aJFUxs.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container6aJFUxs\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container6aJFUxs\App_KernelDevDebugContainer([
    'container.build_hash' => '6aJFUxs',
    'container.build_id' => '388f7d74',
    'container.build_time' => 1654603097,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6aJFUxs');
